# inside .github/workflows/action.yml
name: My docker pyproject
on: push
     branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: My docker pyproject
        uses: vedicsoftcts/pyproject-cts6:1@master
        run: python pyproject1.py
